sudo: false # Explicitly use container-based infrastructure

language: go

go:
    - 1.6
    
env:
    global:
        - BUILDER_VERSION=0.11.0
    matrix:
        - TEST_SUITE=unit
        - TEST_SUITE=integration

cache:
    directories:
        - ./builder-cache

notifications:
    email: false

before_install:
    - openssl aes-256-cbc -K $encrypted_314659c9f31c_key -iv $encrypted_314659c9f31c_iv -in inago-integration-test.pem.enc -out ./inago-integration-test.pem -d
    - cp ./builder-cache/builder-$BUILDER_VERSION ./builder || wget https://downloads.giantswarm.io/builder/$BUILDER_VERSION/builder && chmod +x ./builder
    - chmod +x ./builder
    - export PATH=$PATH:$PWD
    - go get -u github.com/golang/lint/golint

script:
    - ./ci.sh

before_cache:
    - cp ./builder ./builder-cache/builder-$BUILDER_VERSION
