sudo: false # Explicitly use container-based infrastructure

language: go

go:
    - 1.5

notifications:
    email: false

before_install:
- wget https://downloads.giantswarm.io/builder/0.11.0/builder
- chmod +x ./builder
- export PATH=$PATH:$PWD
- go get -u github.com/golang/lint/golint

script:
- make lint
- make ci-test
- make ci-build
- ./formicactl

# codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
