sudo: false # Explicitly use container-based infrastructure

language: go

go:
    - 1.6
    
env:
    - BUILDER_VERSION=0.11.0

cache:
    directories:
    - ./builder-cache

notifications:
    email: false

before_install:
- cp ./builder-cache/builder-$BUILDER_VERSION ./builder || wget https://downloads.giantswarm.io/builder/$BUILDER_VERSION/builder && chmod +x ./builder
- export PATH=$PATH:$PWD
- go get -u github.com/golang/lint/golint

script:
- make lint
- make ci-test
- make ci-build
- ./inagoctl

before_cache:
    - cp ./builder ./builder-cache/builder-$BUILDER_VERSION

# codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
